version: '3.8'
services:
  db:
    image: postgres:15
    container_name: bearpai_db
    restart: always
    environment:
      POSTGRES_USER: bearp_user
      POSTGRES_PASSWORD: bearp_password
      POSTGRES_DB: bearpai_market
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
